#!/bin/sh

set -eu

if [ -z "${YOUTUBE_API_KEY:-}" ]; then
    echo "error: YOUTUBE_API_KEY must be configured as a secret Xcode Cloud environment variable."
    exit 1
fi

if [ -z "${VIDEO_GRABBER_API_TOKEN:-}" ]; then
    echo "error: VIDEO_GRABBER_API_TOKEN must be configured as a secret Xcode Cloud environment variable."
    exit 1
fi

umask 077
printf '%s\n' \
    '// Generated by Xcode Cloud. Do not commit this file.' \
    "YOUTUBE_API_KEY = ${YOUTUBE_API_KEY}" \
    "VIDEO_GRABBER_API_TOKEN = ${VIDEO_GRABBER_API_TOKEN}" \
    > "${CI_PRIMARY_REPOSITORY_PATH}/Config/Secrets.xcconfig"
